CREATE DATABASE BTLIOT1


CREATE TABLE BTLIOT1.dbo.ThongSo (
	id INT IDENTITY(1,1) PRIMARY KEY,
	time NVARCHAR(255),
	nhietdo NVARCHAR(255),
	doam NVARCHAR(255),
	anhsang NVARCHAR(255)
);

CREATE TABLE BTLIOT1.dbo.LichSu (
	id INT IDENTITY(1,1) PRIMARY KEY,
	time NVARCHAR(255),
	doituong NVARCHAR(255),
	trangthai NVARCHAR(255)
);